language: python
python:
  - "3.10"
  - "3.11"
services:
  - redis-server
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
env:
  global:
    - CC_TEST_REPORTER_ID=4af40cead8dc05ea7c5a020df8ff221fa29fd6454c3e3333e70a84b1eb7fc8e1
    - PORT=5037
    - GATEWAY_URL=http://127.0.0.1:9000
    - MICROSERVICE_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    - REDIS_URL=redis://localhost:6379
    - GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_BUILD_DIR}/storage.json
    - AWS_REGION=us-east-1
    - REQUIRE_API_KEY=True
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - echo -e "$EE_PRIVATE_KEY" | base64 -d > privatekey.json
  - echo -e "$GCLOUD_STORAGE" | base64 -d > storage.json
  - pytest --cov=geetiles --cov-report=xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
