version: "3"
services:
  develop:
    build: .
    ports:
      - "5700:5700"
    container_name: gee-tile-develop
    environment:
      PORT: 5700
      ENVIRONMENT: dev
      DEBUG: "True"
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
      EE_PRIVATE_KEY: ${EE_PRIVATE_KEY}
      GCLOUD_STORAGE: ${GCLOUD_STORAGE}
      REDIS_URL: redis://redis:6379
      GOOGLE_APPLICATION_CREDENTIALS: /opt/geetiles/storage.json
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
      AWS_CLOUD_WATCH_LOGGING_ENABLED: "False"
    command: develop
    volumes:
      - ./geetiles:/opt/geetiles/geetiles
    restart: always
    depends_on:
      - redis

  redis:
    image: redis
    restart: always



